Added "-t <TOKEN>" option Updated README.md

diff --git a/src/blackKaliLoader b/src/blackKaliLoader
--- a/src/blackKaliLoader
+++ b/src/blackKaliLoader
@@ -130,10 +130,27 @@ install_ngrok() {
     fi
 }
 
+usage() {
+    echo -e "Syntax Error: Launch script with -t option to set use Ngrok Token"
+    echo -e "Options:\n-t <TOKEN>   | Set a Ngrok Token"
+    echo -e "Example: ./blackkaliloader -t 'mytoken'"
+}
+
 #################### MAIN EXECUTION #####################
+: '
+Setting option -t to set a token before launching the programm
+'
+OPTION=$1
+if [[ $OPTION == '-t' ]]; then
+    NGTOKEN=$2
+else
+    usage
+    exit 1
+fi
+
 header
 echo -e "[+] $(date +%d-%m-%Y_%H:%M:%S) : START"
-check_arch
+#check_arch
 check_ngrok
 if [[ $NGINST = false ]]; then
     install_ngrok
